// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifiiluaowcplcpfmqdtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmaWlsdWFvd2NwbGNwZm1xZHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTM1MTksImV4cCI6MjA2MDQ4OTUxOX0.VO1MJnVmkw5xn4fMEnusj_qfpIEP-7PVC2Gz5NLY3G4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);